FROM openjdk:17-alpine
WORKDIR usr/src
ADD /target/BankApi-0.0.1-SNAPSHOT.jar /usr/src/BankApi-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar", "BankApi-0.0.1-SNAPSHOT.jar"]
ENV MYSQLURL=jdbc:mysql://mysqls:3306/dockdb?createDatabaseIfNotExist=true&user=root&password=password
