server:
  port: 9000
#spring:
#  application:
#    name: samplegeway
#  cloud:
#    gateway:
#      globalcors:
#        cors-configurations:
#          '[/**]':
#              allowedOrigins: "*"
#              allowedMethods: "*"
#              allowedHeaders: "*" 
#      mvc: 
#        routes:
#         - id: restsample
#           uri: http://localhost:9090
#           predicates:
#            - Path=/passenger/**
#         - id: bankapi
#           uri: http://localhost:9098
#           predicates:
#           - Path=/account/**
#   
#      
#        
#
#          
#         