FROM openjdk:17-alpine
WORKDIR usr/src
ADD /target/AuthenticationApp-0.0.1-SNAPSHOT.jar /usr/src/AuthenticationApp-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar", "AuthenticationApp-0.0.1-SNAPSHOT.jar"]
ENV MYSQLURL=jdbc:mysql://mysqls:3306/dockdb?createDatabaseIfNotExist=true&user=root&password=password
ENV EUREKAURL=http://eureka-server:8761/eureka